### ISSUE TITLE
Built zip file not compressed

### ISSUE THREAD

**Issue by RSchwoerer** [docat-org/docatl#6]
The zip file created with the build command is not getting compressed.
Manually zipping the file (with 7zip) gives a file around 4.5mb, using `docatl build` gives a file over 57mb.

Is it possible to have the build command compress the file?

**Comment by fliiiix** [comment]
Hey that sounds like a great feature! Do you mind creating a pull request for that?I think we can achieve something by passing some flags to the go archiver around here:https://github.com/docat-org/docatl/blob/7ccd1774f2bf2b733b4b765902761723d7d9b433/pkg/build.go#L51

**Comment by RSchwoerer** [comment]
I looked briefly at the archiver library being used, it does look like there simply needs to be a parameter. 

Unfortunately I’m not a Go developer and probably don’t have much time to get an environment all set up to be able to build this. Otherwise I’d be happy to just submit a PR.

**Comment by RSchwoerer** [comment]
👏 nice! I will try to get our server updated and try it out.

**Comment by fliiiix** [comment]
in my testing the docatl zip was still a bit bigger but i guess that should be good enough now
```
7.1M	6.3.3.zip # created with zip
7.2M	6.3.3.zip # created with docatl
```
